"""Install the auto-loading peaksMCP kernelspec."""

from __future__ import annotations

import json
import shutil
import sys
import tempfile
from pathlib import Path
from typing import Any

from jupyter_client.kernelspec import KernelSpecManager, NoSuchKernel

from .profiles import Profile


def kernel_profile_state(profile: Profile) -> dict[str, Any]:
    """Return every profile value baked into or inherited by the kernel."""
    return {
        "profile": profile.name,
        "mode": profile.mcp.mode,
        "autostart": profile.mcp.autostart,
        "host": profile.mcp.host,
        "port": profile.mcp.port,
        "allow_remote": profile.mcp.allow_remote,
    }


def _startup(profile: Profile) -> str:
    # Embed profile values as JSON string literals so configuration containing
    # quotes/newlines cannot break out of the generated startup source.
    host = json.dumps(profile.mcp.host)
    port = json.dumps(str(profile.mcp.port))
    mode = json.dumps(profile.mcp.mode)
    allow_remote = json.dumps("true" if profile.mcp.allow_remote else "false")
    autostart = json.dumps("true" if profile.mcp.autostart else "false")
    return f'''# Generated by peaksMCP install-kernel.
def _peaksmcp_start():
    import os
    from IPython import get_ipython
    # Defaults baked from the installing profile; a supervisor overrides these
    # through the inherited environment so separate profiles/tests never collide
    # on the MCP port.
    os.environ.setdefault("PEAKSMCP_HOST", {host})
    os.environ.setdefault("PEAKSMCP_PORT", {port})
    os.environ.setdefault("PEAKSMCP_MODE", {mode})
    os.environ.setdefault("PEAKSMCP_ALLOW_REMOTE", {allow_remote})
    os.environ.setdefault("PEAKSMCP_AUTOSTART", {autostart})
    ip = get_ipython()
    if ip is None:
        return
    try:
        ip.run_line_magic("load_ext", "peaksMCP.server.jupyter_peaks.jupyter_mcp_extension")
    except Exception as exc:
        print(f"[peaksMCP] auto-start failed: {{exc}}")

import asyncio
asyncio.get_event_loop().call_later(0.5, _peaksmcp_start)
'''


def install_kernel(profile: Profile, replace: bool = True) -> Path:
    """Install a kernelspec whose startup script loads the MCP extension."""
    manager = KernelSpecManager()
    with tempfile.TemporaryDirectory(prefix="peaksmcp-kernel-") as temporary:
        source = Path(temporary)
        kernel = {
            "argv": [sys.executable, "-m", "ipykernel_launcher", "-f", "{connection_file}", "--IPKernelApp.exec_files={resource_dir}/peaksmcp_startup.py"],
            "display_name": f"Python (peaksMCP · {profile.mcp.mode})",
            "language": "python",
            "metadata": {
                "peaksMCP": kernel_profile_state(profile)
            },
        }
        (source / "kernel.json").write_text(json.dumps(kernel, indent=2) + "\n", encoding="utf-8")
        (source / "peaksmcp_startup.py").write_text(_startup(profile), encoding="utf-8")
        manager.install_kernel_spec(str(source), kernel_name=profile.jupyter.kernel_name, user=True, replace=replace)
    return Path(manager.get_kernel_spec(profile.jupyter.kernel_name).resource_dir)


def uninstall_kernel(name: str = "peaksmcp") -> bool:
    """Remove the named peaksMCP kernelspec."""
    manager = KernelSpecManager()
    try:
        path = Path(manager.get_kernel_spec(name).resource_dir)
    except NoSuchKernel:
        return False
    shutil.rmtree(path)
    return True


def kernel_installed(name: str = "peaksmcp") -> bool:
    """Return whether the target kernelspec exists."""
    return name in KernelSpecManager().find_kernel_specs()


def kernel_spec_state(name: str = "peaksmcp") -> dict[str, Any] | None:
    """Read all security- and endpoint-sensitive peaksMCP kernelspec settings.

    Returns ``None`` when the kernelspec is missing or has no peaksMCP metadata.
    """
    try:
        path = Path(KernelSpecManager().get_kernel_spec(name).resource_dir) / "kernel.json"
        kernel = json.loads(path.read_text(encoding="utf-8"))
    except (KeyError, NoSuchKernel, OSError, json.JSONDecodeError):
        return None
    metadata = kernel.get("metadata", {}).get("peaksMCP") or {}
    if not metadata:
        return None
    return {
        key: metadata.get(key)
        for key in ("profile", "mode", "autostart", "host", "port", "allow_remote")
    }
