const $=s=>document.querySelector(s);const pretty=x=>JSON.stringify(x,null,2);let records=[];
function renderComponents(s){$('#profile').textContent=`profile: ${s.profile}`;$('#state').textContent=(s.aggregate||s.status).toUpperCase();$('#open-lab').href=s.notebook_open_url||s.notebook_url;$('#components').innerHTML=Object.entries(s.components||{}).map(([name,c])=>`<article class="component ${c.state}"><b>${name}</b><span>${c.state.toUpperCase()}</span><span>${c.detail}</span></article>`).join('')}
async function refresh(){try{renderComponents(await fetch('/api/status').then(r=>r.json()))}catch(e){$('#state').textContent='OFFLINE'}}
function renderImages(value){const blocks=value?.result||[];$('#images').innerHTML=Array.isArray(blocks)?blocks.filter(x=>x.type==='image').map(x=>`<img alt="Notebook output" src="data:${x.mimeType};base64,${x.data}">`).join(''):''}
$('#search').addEventListener('submit',async e=>{e.preventDefault();$('#result').textContent='Searching…';const body={name:'peaks_search_api',arguments:{query:$('#query').value,limit:8}};const r=await fetch('/api/mcp/tool',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)}).then(x=>x.json());$('#result').textContent=pretty(r);renderImages(r)});
document.querySelectorAll('[data-restart]').forEach(b=>b.addEventListener('click',async()=>{b.disabled=true;$('#action-result').textContent=`Restarting ${b.dataset.restart}…`;const r=await fetch(`/api/restart/${b.dataset.restart}`,{method:'POST'}).then(x=>x.json());$('#action-result').textContent=pretty(r);b.disabled=false;refresh()}));
$('#doctor-button').addEventListener('click',async()=>{$('#doctor').textContent='Running…';$('#doctor').textContent=pretty(await fetch('/api/doctor').then(r=>r.json()))});
$('#convert').addEventListener('submit',async e=>{e.preventDefault();$('#convert-result').textContent='Converting…';const body={input:$('#pxt-input').value,output:$('#pxt-output').value||null,metadata:$('#pxt-metadata').value||null};$('#convert-result').textContent=pretty(await fetch('/api/convert',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)}).then(r=>r.json()))});
function renderLogs(){const filter=$('#log-filter').value;$('#logs').textContent=records.filter(x=>!filter||x.component===filter).map(x=>`[${x.component}] ${x.message}`).join('\n');const values=new Set([...$('#log-filter').options].map(x=>x.value));for(const c of new Set(records.map(x=>x.component))){if(!values.has(c))$('#log-filter').add(new Option(c,c))}}
$('#log-filter').addEventListener('change',renderLogs);const ws=new WebSocket(`${location.protocol==='https:'?'wss':'ws'}://${location.host}/ws/logs`);ws.onopen=()=>$('#connection').classList.add('up');ws.onclose=()=>$('#connection').classList.remove('up');ws.onmessage=e=>{const d=JSON.parse(e.data);records=records.concat(d.logs||[]).slice(-1000);renderLogs()};fetch('/api/profiles').then(r=>r.json()).then(x=>$('#profiles').textContent=pretty(x));refresh();setInterval(refresh,5000);
